# Build images from the Dockerfiles and post it on Dockerhub

name: Docker CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: docker login
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: | 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker build php74alpine
        run: |
          docker build ./php74alpine -t betoscopio/php74alpine-ext:latest
          docker build ./php74alpine-D7 -t betoscopio/betoscopio/php74alpine-d7:latest
      
      - name: Docker build php74alpine D8
        run: |
          docker build ./php74alpine-D8 -t betoscopio/betoscopio/php74alpine-d8:latest

      - name: Docker push
        run: |
          docker push betoscopio/php74alpine-ext:latest
          docker push betoscopio/php74alpine-D7:latest
          docker push betoscopio/php74alpine-D8:latest
